### ISSUE TITLE
Google Login on Trello

### ISSUE THREAD

**Issue by david02871** [mmazzarolo/react-native-trello-login#1]
I am getting an error message while trying to use my Google login for Trello which seems to be related to the use of the webview. 

"This user-agent is not permitted to make OAuth authorisation request to Google as it is classified as an embedded user-agent (also known as a web-view). Per our policy, only browsers are permitted to make authorisation requests to Google."

"Error: disallowed_useragent

Google can't sign you in safely inside this app."

**Comment by mmazzarolo** [comment]
Hey, I don't think it would be possible to fix it.   
As you can see from the error message you can't start a Google login using a WebView.
